
########################################### API URLS ##############################################

update.acc.url = https://sandbox.stitch.sa/v1/transactions
close.acc.url =https://sandbox.stitch.sa/v1/transactions/{transactionId}/expire
add.acc.url = https://sandbox.stitch.sa/v1/transactions/{transactionId}/reverse
delete.DLT.acc.url =https://sandbox.stitch.sa/v1/transactions/{transactionId}/settle

########################################### Threads ###########################################

thread.pool.size=30
########################################### DB connection ###########################################


DBJNDI=java:comp/env/jdbc/paybycus
################################### poller time  #################################

cron.expression.updateAccount=0/2 * * * * ?
cron.expression.closeAccount=0/2 *  * * * ?
cron.expression.addAccount=0/2 *  * * * ?
cron.expression.deleteAccount=0/2 *  * * * ?
cron.expression.requestStatus=0/2 *  * * * ?


################################### Scheduler #################################
################################### stop = false ,start = true #################################


scheduler.enable.updateAccount=true
scheduler.enable.closeAccount=true
scheduler.enable.addAccount=true
scheduler.enable.deleteAccount=true
scheduler.enable.requestStatus=true

