consumerKey=IWJUQ6lWmWBRrCLmgTCrQqtMYndofgqREKnv-BnAc0aeab40!68859f3f1be14ccc823c9eeaf34e8aec0000000000000000
keyAlias=mastercard
keyPassword=mastercard@123
signingkeypath=/home/user/Documents/INSTAPAY/KEYS/mastercard-sandbox.p12
encryptioncerpath=/home/user/Documents/INSTAPAY/KEYS/payment-account-management-ClientEnc1773049493568.pem
certificatefingerprint=76f2d3663367725da353ca899d3594f1ffa4b48ff7e90c9d7ff175860436e959