

URL=jdbc:oracle:thin:@//172.22.26.119:1522/orclycs
USERNAME=DLULUCUDB
PASSWORD=DLULUCUDB



# consumerKey=Zk16X2l6R0liYW5xNHRwNFI5YXVob2U3X2xFUTJXcGxncXdnbVg5N2ZkYmIyYzVjJTIxMzUyYjVjNjNlN2UzNDI0M2EyZjY3YTBkNjYwZDI2ODMwMDAwMDAwMDAwMDAwMDAw

# keyAlias=a2V5YWxpYXM=

# keyPassword=a2V5c3RvcmVwYXNzd29yZA==

# signingkeypath=/home/user/Documents/INSTAPAY/KEYS/Payby_MDES_Project_-sandbox.p12

# encryptioncerpath=/home/user/Documents/INSTAPAY/KEYS/public-key-certificate.crt

# certificatefingerprint=243e6992ea467f1cbb9973facfcc3bf17b5cd007

# SearchTokenUrl=http://localhost:8080/paybymdescustomerservice/Mdesapi/TokenSearch?CardNo=

# TokenActionUrl=http://localhost:8080/paybymdescustomerservice/Mdesapi/TokenAction?

# URL=amRiYzpvcmFjbGU6dGhpbjpALy8xNzIuMjIuMjYuMTE5OjE1MjIvb3JjbHljcw==

# Time.For.DeleteToken=20000

# PASSWORD=RExVTFVDVURC

# USERNAME=RExVTFVDVURC

# Closuresql=SELECT CM.PACKREFNO,TTA.TOKENUNIQUEREFERENCE FROM CARD_MASTER CM,TOKEN_TXN_API TTA WHERE CM.CARD_NO=TTA.ACCOUNTPAN  AND CM.CARD_STATUS='C' AND  CURRENTSTATUSCODE NOT IN('D') AND ROWNUM<2

# CLOSURE_SEARCH_QUERY=SELECT DISTINCT CM.PACKREFNO FROM CARD_MASTER CM,CLOSED_CARD_DETAILS CCD WHERE CM.CARD_NO=CCD.CARD_NO AND CM.CARD_STATUS='C' AND CCD.SEARCH_FLAG='P'

# CLOSURE_DELETE_QUERY=SELECT DISTINCT CM.PACKREFNO,TTA.TOKENUNIQUEREFERENCE FROM CARD_MASTER CM,TOKEN_TXN_API TTA,CLOSED_CARD_DETAILS CCD WHERE CM.CARD_NO=TTA.ACCOUNTPAN AND CM.CARD_NO=CCD.CARD_NO AND CM.CARD_STATUS='C' AND CURRENTSTATUSCODE NOT IN('D') AND CCD.SEARCH_FLAG='C' AND TTA.CLOSURE_FLAG='P' AND ROWNUM<2

